import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="next">
      <Head>
        <title>My Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="main-wraper">
        
      </main>
    </div>
  )
}

export default Home
