import type { NextPage } from 'next'
import Head from 'next/head'
import Particles from "react-tsparticles";
import particlesOptions from "./particles.json";
import { ISourceOptions } from "tsparticles";

const Home: NextPage = () => {
  
  return (
    <div className="next">
      <Head>
        <title>My Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="main-wraper">        
        <Particles options={particlesOptions as ISourceOptions}/>
      </main>
    </div>
  )
}

export default Home
