import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="next">
      <Head>
        <title>My Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="main-wraper">
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className='text-36 font-medium text-red-300'>tailwind css testing</div>        
      </main>
    </div>
  )
}

export default Home
