import type { NextPage } from 'next'
import Head from 'next/head'
import Particles from "react-tsparticles";
import particlesOptions from "./particles.json";
import { ISourceOptions } from "tsparticles";

const Home: NextPage = () => {
  
  const particlesInit = (main:any) => {
    console.log(main);

    // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
  };

  const particlesLoaded = (container:any) => {
    console.log(container);
  };
  return (
    <div className="next">
      <Head>
        <title>My Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        
      </Head>
      <main className="main-wraper">
      
      <Particles options={particlesOptions as ISourceOptions}/>

      </main>
    </div>
  )
}

export default Home
